# Generated by Django 5.2 on 2025-06-15 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('veterinario', 'Veterinario'), ('estetico', 'Estético')], max_length=20)),
                ('tipo_reserva', models.CharField(choices=[('presencial', 'Presencial'), ('domicilio', 'A domicilio')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
