# Generated by Django 5.2 on 2025-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20),
        ),
    ]
