# Generated by Django 5.2 on 2025-06-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_direccion_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_camino', 'En camino'), ('en_espera', 'En espera'), ('en_atencion', 'En atención'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20),
        ),
    ]
