# Generated by Django 5.2 on 2025-06-16 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(limit_choices_to={'tipo_usuario': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='core.fichamedica')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('chip', models.CharField(blank=True, max_length=30, null=True)),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='core.dueno')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.mascota'),
        ),
        migrations.CreateModel(
            name='ServicioDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('reserva', models.OneToOneField(limit_choices_to={'tipo_reserva': 'domicilio'}, on_delete=django.db.models.deletion.CASCADE, to='core.reserva')),
            ],
        ),
    ]
