# Generated by Django 5.2 on 2025-06-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mascota_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciodomicilio',
            name='equipo',
            field=models.CharField(max_length=255),
        ),
    ]
