# Generated by Django 5.2 on 2025-06-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_serviciodomicilio_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciodomicilio',
            name='equipo',
        ),
        migrations.AddField(
            model_name='serviciodomicilio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviciodomicilio',
            name='horario_asignado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciodomicilio',
            name='num_estilistas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviciodomicilio',
            name='num_veterinarios',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviciodomicilio',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
