# Generated by Django 5.2 on 2025-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_serviciodomicilio_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='perro', max_length=20),
        ),
    ]
