# Generated by Django 5.2 on 2025-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mascota_especie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
