# Generated by Django 5.2 on 2025-06-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fichamedica_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichamedica',
            name='peso',
        ),
        migrations.AddField(
            model_name='entrada',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
