# Generated by Django 5.2 on 2025-06-17 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_fichamedica_peso_entrada_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medicamentos', models.TextField(help_text='Indicar nombre comercial, dosis, vía y frecuencia.')),
                ('indicaciones_generales', models.TextField(blank=True, help_text='Instrucciones adicionales para el dueño.')),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='core.entrada')),
                ('firmado_por', models.ForeignKey(limit_choices_to={'tipo_usuario': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
