# Generated by Django 5.2 on 2025-06-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='tratamiento',
            field=models.TextField(blank=True, help_text='Detalle del procedimiento realizado'),
        ),
    ]
